---
apiVersion: v1
kind: Service
metadata: 
  name: hello-svc
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: http
  type: LoadBalancer
...

#kubectl apply -f backendService.yaml