---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
...

#kubectl apply -f backendService.yaml