---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: db
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo
        tier: db        
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017        
...