ARG VERSION=2.2
ARG	PORT_APP=80

FROM mcr.microsoft.com/dotnet/core/aspnet:$VERSION AS base
#ENV HTTP_PROXY "http://10.20.14.35:8080" \
#	HTTPS_PROXY "http://10.20.14.35:8080"
ENV HTTP_PROXY=http://mcafeeproxy01.ntdomain.educ.gov.il:8080 \
	HTTPS_PROXY=http://mcafeeproxy01.ntdomain.educ.gov.il:8080 \
	http_proxy=http://mcafeeproxy01.ntdomain.educ.gov.il:8080 \
	https_proxy=http://mcafeeproxy01.ntdomain.educ.gov.il:8080 \
	no_proxy=dskmalamj025
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["kubernetis/kubernetis.csproj", "kubernetis/"]
RUN dotnet restore "kubernetis/kubernetis.csproj"
COPY . .
WORKDIR "/src/kubernetis"
RUN dotnet build "kubernetis.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "kubernetis.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "kubernetis.dll"]